# Usage example:
# crowdin download -v -l es-ES -i PROJECT_ID -T API_TOKEN
# https://crowdin.github.io/crowdin-cli/

# Required by CLI
base_path: .
preserve_hierarchy: true

files:
  - source: /app/src/main/res/values/preferences.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    skip_untranslated_strings: true
    languages_mapping:
      android_code:
        da: da
        es-ES: es
        fi: fi
        fr: fr
        it: it
        ja: ja
        nl: nl
        pl: pl
        pt-PT: pt
        ru: ru
        sv-SE: sv
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    skip_untranslated_strings: true
    languages_mapping:
      android_code:
        da: da
        es-ES: es
        fi: fi
        fr: fr
        it: it
        ja: ja
        nl: nl
        pl: pl
        pt-PT: pt
        ru: ru
        sv-SE: sv

# GitHub integration
pull_request_title: Update translations via Crowdin.
pull_request_labels:
  - Translation
commit_message: Update %language% translation (%original_file_name%).
append_commit_message: false
