files:
  - source: /app/src/main/res/values/*.xml
    ignore:
      - attrs.xml
      - booleans.xml
      - colors.xml
      - dimens.xml
      - colors_congress.xml
      - integers.xml
      - placeholder.xml
      - styles_congress.xml
    translation: app/src/main/res/values-%two_letters_code%/%original_file_name%
